---
output: github_document
---

```{r}
# Importing the data set 
library(readxl)
state<-read_excel("STATE_ED_1997_corrected.xlsx")
state
names(state)
```

```{r}
#==== Assumptions required for multiple linear regression ====
# (1) Normality - all variables should be quantitative and normally distributed with no extreme outliers
# (2) Linearity - all pairs of variables must be linearly related
# (3) No multicollinearity - X1 and X2 are not highly correlated
# (4) No interactions between X1 and X2 as predictors of Y - slope relating Y and X1 must not differ across levels of X2

Y <- state$Expenditure_per_Pupil
X1 <- state$Average_Annual_Salary_for_Public
X2 <- state$Pupils_per_Teacher

# Getting descriptive statistics for each variable 
summary(state$Average_Annual_Salary_for_Public)
  sd(state$Average_Annual_Salary_for_Public)
summary(state$Pupils_per_Teacher)
  sd(state$Pupils_per_Teacher)
summary(state$Expenditure_per_Pupil)
  sd(state$Expenditure_per_Pupil)

# Boxplots to check for outliers 
boxplot(state$Average_Annual_Salary_for_Public, 
  main = "Average Annual Salary for Public School Teachers")
  # no outliers 
boxplot(state$Pupils_per_Teacher, 
  main = "Average Number of Pupils per Teacher")
  # 2 outliers 
boxplot(state$Expenditure_per_Pupil, main = "Average Expenditure per Pupil")
  # 3 outliers 
## outliers do not appear to be extreme enough to have significant impact on the data - mean and median are relatively close meaning outliers do not have much of an effect, they will be kept in data set. 

# Histograms to check (1)
hist(state$Average_Annual_Salary_for_Public, 
     main = "Average Annual Salary for Public School Teachers")
hist(state$Pupils_per_Teacher, 
     main = "Average Number of Pupils per Teacher")
hist(state$Expenditure_per_Pupil, 
     main = "Average Expenditure per Pupil")
## all variables are approximately normally distributed 

# Scatter plots for all pairs of variables 
pairs(state[,4:6], upper.panel = NULL)  

# Zero order correlation coefficients 
cor(state$Average_Annual_Salary_for_Public, state$Expenditure_per_Pupil)
cor(state$Pupils_per_Teacher, state$Expenditure_per_Pupil)
cor(state$Average_Annual_Salary_for_Public, state$Pupils_per_Teacher)
## Scatter plots show a linear relationship between X1 & Y and X2 & Y, but it seems X1 & X2 are not linearly related. This could be a possible violation of assumption (2). Correlation coefficients show high positive correlation btwn X1 and Y, moderate negative correlation btwn X2 and Y, and a very weak correlation between X1 and X2. Assumption (2) is partially met, and assumption (3) is met.

# Scatter plot w/ fit line not accounting for X2
library(ggplot2)
ggplot(state, aes(x=Average_Annual_Salary_for_Public, y=Expenditure_per_Pupil)) +
  geom_point(size=2, alpha=.5, aes(color=factor(Pupils_per_Teacher))) +
  theme_classic() + 
  labs(color="Avg Pupils per Teacher") + 
  geom_smooth(method = lm, color="black") + 
  scale_color_discrete(name = "Avg Pupils per Teacher")

# Scatter plot with fit line for each level of X2                                                   (binned intervals of 1)
intervals <- seq(13, 24, by = 1)
state$bins <- cut(state$Pupils_per_Teacher, breaks = intervals)
library(ggplot2)
ggplot(state, aes(x = Average_Annual_Salary_for_Public, y = Expenditure_per_Pupil)) +
  geom_point(alpha = 0.5, size = 2, aes(color = bins)) +
  geom_smooth(method = "lm", se = FALSE, aes(group = bins)) +
  scale_color_discrete(name = "Avg Pupils per Teacher") +
  labs(x = "Average Annual Salary for Public", y = "Expenditure per Pupil") +
  theme_classic() +
  facet_wrap(~ bins)
## Assumption (4) met - no interaction between X1 and X2 as predictors of Y,
  #slopes of fit lines do not change too much between levels of X2
  #slope of fit line in 1st plot seems to be on average slightly steeper than the slopes of the lines in 2nd plot but not too much 
```

```{r}
#==== Hypotheses ====
# Null Hypothesis 1 - H0: b1 = 0
# Alt Hypothesis 1 - H1: b1 dne 0

# Null Hypothesis 2 - H0: b2 = 0
# Alt Hypothesis 2 - H1: b2 dne 0
```

```{r}
#==== Fitting Regression Model ====
model1<-lm(state$Expenditure_per_Pupil~state$Average_Annual_Salary_for_Public+state$Pupils_per_Teacher)
analysis<-summary(model1)
analysis
## overal model significant: 
  # R^2=0.8606 
  # F(2,47)=152.3, p<.001
## Individual predictors significant:
  # b(.19),t(47) = 16.028 -> sig positive relationship 
  # b(-228.04807),t(47) = -6.964 -> sig negative relationship 
```

```{r}
# ==== ANOVA Table ====
anova(model1)
# Individual F values both significant:
  ## F(1,47)=256.1, p<.001
  ## F(1,47)=48.5, p<.001
```

```{r}
# ==== R Squared ====
analysis$r.squared
## 86.06% of the variance in Y explained by X1 and X2
## indicates strong relationship and practical significance 
```

```{r}
# ==== Confidence Intervals ====
confint(model1, level = 0.95) 
# doesn't contain 0 - statistically signif.
# coefficients are within intervals, indicating practical signif. 
```

```{r}
# ==== Plotting Regression Model ====
library(car)
avPlots(model1)

```

```{r}
# ==== Checking Residuals ====
par(mfrow=c(2,2))
plot(model1)
library(olsrr)
ols_test_normality(model1)
## Residuals Assumptions:
# 1. normality and homogenity of variance 
# 2. residuals are independent 
  ## both assumptions met 
```
